version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - postgres-db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres-db:5432/postgres
      PASSWORD_HASH_SALT: uRQQZ!oQw)qyKJtLB/sd
      JWT_SECRET: 92e1f07ddb3caa02b2298f1fedf0a1fed5bf05ee33e4d15873354a474d43343d

  postgres-db:
    image: postgres
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db-data:
