version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - postgres-db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  postgres-db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db-data:
