"""create geolocation table

Revision ID: v0.2
Revises: v0.1
Create Date: 2021-11-16 20:12:25.284050

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "v0.2"
down_revision = "v0.1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geolocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("continent_code", sa.String(length=5), nullable=True),
        sa.Column("continent_name", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=5), nullable=True),
        sa.Column("country_name", sa.String(length=255), nullable=True),
        sa.Column("region_code", sa.String(length=5), nullable=True),
        sa.Column("region_name", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("zip", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip", name="geolocation_ip_unique_constraint"),
        sa.UniqueConstraint("url"),
        sa.UniqueConstraint("url", name="geolocation_url_unique_constraint"),
        schema="schema",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geolocation", schema="schema")
